[project]
name = "adum"
version = "0.1.1"
description = "ADUM Python Scrapper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "dotenv>=0.9.9",
    "gotify>=0.6.0",
    "icalendar>=6.3.2",
    "requests>=2.32.5",
]
